@startuml
!pragma PLS 8192

skinparam maxMessageSize 200
autonumber
hide unlinked
scale 1625 width

actor "LE-DE" as User
box "EU-Webportal" #AliceBlue
    participant "WebApp" as WebApp
end box
box "Hilfsmittel" #WhiteSmoke
    participant "gematik\nAuthenticator" as AuthApp
    participant "Konnektor" as Konnektor
    participant "IDP-Dienst" as IDP
end box
box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as Proxy
    participant "Auth-Service" as AuthService
end box
participant "NCPeH-FD" as NCPeH

== 1. Start EU-Webportal und Authentifizierung ==

group#Gold ref
    User -> WebApp: UC "Basis-Initialisierung der WebApp und der Kommunikation"
    activate WebApp
end

User -> WebApp: Klick auf "Anmelden"

opt Falls DPoP-Schlüsselpaar noch nicht vorhanden
  WebApp -> WebApp: Asymmetrisches Schlüsselpaar generieren (PrK, PuK)
  note left #Yellow
    Domänenobjekt:
    ""DPoPAsymmetricKeyPair""
  end note
end

WebApp -> WebApp: DPoP-Proof JWT generieren (PrK, ...): DPoP-Token-1

WebApp -> Proxy: Decoupled Auth Request POST /auth-decoupled
activate Proxy
Proxy -> AuthService: Request weiterleiten
deactivate Proxy

activate AuthService
AuthService -> AuthService: Erstelle PKCE (Code Verifier, Challenge, state)
AuthService -> AuthService: Erzeuge auth_req_id:auth_req_id
AuthService -> AuthService: Autorisierungsauftrag speichern (auth_req_id, Code Verifier, state, ...)
note left #Yellow
    Domänenobjekt:
    ""AuthorizationTask""
end note
AuthService --> Proxy: 200 OK Decoupled Authorization Response (:auth_req_id, :poll_uri, :redirect_uri, expires_in, interval)
note left
    redirect_uri enthält neben Endpoint Adresse des IDP
    u.a. folgende Requestparameter und Werte:
    ""response_type=code""
    ""client_id=<CLIENT_ID>"" **statisch, durch Registrierung am IDP zugewiesen**
    ""scope=<SCOPE>"" **Muss im zIDP konfiguriert werden im zIDP bei Client-Reg.**
    ""redirect_uri=Auth-Endpoint am NCPeH-Auth-Service""
    ""state=<STATE>""
    ""code_challenge=<PKCE CHALLENGE_HASH>""
    ""code_challenge_method=S256""
end note
activate Proxy
Proxy --> WebApp: Response weiterleiten
deactivate Proxy

par Authenticator Flow

    WebApp -> AuthApp: Deeplink Aufruf authenticator://... (challenge_path=redirect_uri, callback=direct, cardType=multi)

    activate AuthApp
    loop durchführen, jeweils einmal für HBA und einmal für SMC-B mit Loop-Variable [n]
        AuthApp -> IDP: GET /auth?...
        activate IDP
        IDP --> AuthApp: :Challenge, :User Consent

        == 2. Consent und Karteninteraktion ==

        group User Consent
            AuthApp -> User: displayConsent(User Consent)
            User --> AuthApp: User Consent erteilt
        end

        opt User Consent hergestellt
            AuthApp -> Konnektor: ExternalAuthenticate (CardHandle=<aktuelle Karte aus [n]>, Challenge)
            activate Konnektor
            opt falls PIN nicht gecached
                Konnektor -> User: PIN Abfrage am eH-KT für abgelaufene Freigabe
                User --> Konnektor: Pin-Eingabe am eH-KT (:PIN)
            end
            Konnektor --> AuthApp: ExternalAuthenticateResponse (:signierte Challenge)
            deactivate Konnektor

            AuthApp -> IDP: POST /auth (signierte Challenge)
        end

        IDP -> IDP: Validiere (Signatur, Zertifikate)

        == 3. AUTH_CODE Grant ==

        opt Validierung erfolgreich
            IDP -> AuthApp: 302 Redirect zu redirect_uri vom NCPeH-Auth-Service (code=<AUTH_CODE>)
            AuthApp -> Proxy: Aufruf Auth-Endpoint /GET (code, state, redirect_uri)
            activate Proxy           
            Proxy -> AuthService: Request weiterleiten
            deactivate Proxy
            AuthService -> AuthService: Autorisierungsauftrag finden (state):Autorisierungsauftrag
            AuthService -> AuthService: Autorisierungsauftrag ergänzen (code)
            AuthService --> AuthApp: 200 OK
        end

        == 4. TokenExchange Auth-Code zu ID-Token ==


        AuthService -> Proxy: POST /token (code, Code Verifier)
        activate Proxy
        Proxy -> IDP: Request weiterleiten
        deactivate Proxy

        IDP -> IDP: Token Request validieren (code, Code Verifier)
        IDP --> Proxy: 200 OK (:id_token[n])
        activate Proxy
        Proxy --> AuthService: Response weiterleiten
        deactivate Proxy
        deactivate IDP
        AuthService -> AuthService: Autorisierungsauftrag ergänzen (id_token[n])
    end
            AuthApp -> AuthApp: Authenticator wird beendet
            destroy AuthApp

    == 5. erneuter TokenExchange und Polling durch EU-Webportal ==
    AuthService -> AuthService: Tokens validieren (Autorisierungsauftrag.id_token[1..2])

    group Policy für neues Access-Token "ncpehprx_access_token"
        AuthService -> AuthService: Prüfe ExchangePolicy (id_token[1..2])
        note left
            ""grant_type=urn:ietf:params:oauth:grant-type:token-exchange""
            ""subject_token=<id_token>""
            ""subject_token_type=urn:ietf:params:oauth:token-type:id_token""
            ""requested_token_type=urn:ietf:params:oauth:token-type:access_token""
            **""audience=ncpeh-proxy""**
        end note
        note right #Yellow
            Domänenobjekt:
            ""ExchangePolicy""
        end note
        AuthService -> AuthService: Prüfung der Rolle des LE-DE auf Zugriffsberechtigung (id_token[1..2].Claims)
        AuthService -> AuthService: Generiere neues ncpehprx_access_token (id_token[1..2]):ncpehprx_access_token
    end
    group Policy für neues ID-Token "IdA_raw"
        AuthService -> AuthService: Prüfe ExchangePolicy (id_token[1..2])
        note left
            ""grant_type=urn:ietf:params:oauth:grant-type:token-exchange""
            ""subject_token=<id_token>""
            ""subject_token_type=urn:ietf:params:oauth:token-type:id_token""
            ""requested_token_type=urn:ietf:params:oauth:token-type:id_token""
            **""audience=ncpeh-fd""**
        end note
        note right #Yellow
            Domänenobjekt:
            ""ExchangePolicy""
        end note
        AuthService -> AuthService: Mapping der Claims (id_token[1..2].Claims):IdA_Claims
        AuthService -> AuthService: Generiere und signiere neue IdA-Vorstufe als ID-Token (IdA_Claims):IdA_raw
    end
    group Policy für neues ID-Token "euwp_id_token"
        AuthService -> AuthService: Prüfe ExchangePolicy (id_token[1..2])
        note left
            ""grant_type=urn:ietf:params:oauth:grant-type:token-exchange""
            ""subject_token=<id_token>""
            ""subject_token_type=urn:ietf:params:oauth:token-type:id_token""
            ""requested_token_type=urn:ietf:params:oauth:token-type:id_token""
            **""audience=eu-webportal""**
        end note
        note right #Yellow
            Domänenobjekt:
            ""ExchangePolicy""
        end note
        AuthService -> AuthService: Mapping der Claims (id_token[1..2].Claims):Disp_Claims
        AuthService -> AuthService: Generiere und signiere ID-Token (Disp_Claims):euwp_id_token
    end

    AuthService -> AuthService: Autorisierungsauftrag ergänzen (ncpehprx_access_token, IdA_raw, euwp_id_token)

else EU-Webportal pollt

    loop solange Pollen, bis expires_in erreicht ist, alle Sekunden gemäß interval
        WebApp -> Proxy: Access-Token Request POST poll_uri (auth_req_id, DPoP-Token-1, PuK, ...)
        note left
            Polling mit DPoP-Token-1 und PuK
            zur Bindung der Access-Token-Response
            an den ursprünglichen
            Authentifizierungsversuch.
        end note
        activate Proxy
        Proxy -> AuthService: Request weiterleiten
        deactivate Proxy
        AuthService -> AuthService: Autorisierungsauftrag prüfen, ob ncpehprx_access_token vorliegt (auth_req_id)
        alt ncpehprx_access_token noch nicht vorhanden
            AuthService --> Proxy: 201 Created
            activate Proxy
            Proxy --> WebApp: Response weiterleiten
            deactivate Proxy
            note left
                Status:
                ""WAITING_FOR_AUTHENTICATOR_RESPONSE""
            end note
        else #MistyRose Poll Fehler     
            AuthService --> Proxy: 400 Bad Request (Error)
            activate Proxy
            Proxy --> WebApp: Response weiterleiten
            deactivate Proxy
        else ncpehprx_access_token vorhanden

            AuthService -> AuthService: DPoP-Token validieren (DPoP-Token-1, PuK, ...)
            AuthService -> AuthService: im ncpehprx_access_token inkludiertem JWK-Thumbprint ergänzen (DPoP-Token-1, PuK):ncpehprx_access_token

            AuthService --> Proxy: 200 OK (:ncpehprx_access_token, :euwp_id_token)
            activate Proxy
            Proxy --> WebApp: Response weiterleiten
            deactivate Proxy
             note left
                Status: ""AUTHENTICATED""
             end note
        end
    end
|||
end

AuthService --> Proxy: 200 OK (:IdA_raw)
deactivate AuthService
activate Proxy

== 6. Backend-Zugriff ==

deactivate AuthService

opt ASL-Kanal noch nicht etabliert
    group#Gold ref
        WebApp -> NCPeH: UC "Etablierung eines ASL-Kanals in die VAU-Umgebung des NCPeH-FD"
    end
end

group#Gold ref
    User -> NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD"
end
@enduml