@startuml ISM_bereitstellen_detailed

skinparam maxMessageSize 200
hide unlinked
'autonumber

actor "LE-DE" as User

participant "EU-Webportal\n(im Browser)" as WebApp
control "Buildprozess\n(im Hintergrund)" as Buildprozess
database "Quellcode-Repository" as SrcRepo
participant "Translation Service" as TranslationService

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as Proxy
end box

actor "Systemadministrator" as Administrator
box "NCPeH-FD" #EAF2F8
control "Scheduler" as Scheduler <<internal>>
participant "NCPeH-FD" as NCPeH
end box

participant "eHDSI Configuration Service" as ConfServ

== Vorbedingungen ==
Administrator -> Scheduler: legt an
opt manuelle Übersetzung von ISMs gewünscht
    Administrator -> Proxy: erstellt lektorierte, manuelle Übersetzung der ISMs
end
== 1. Täglicher Abruf von ServiceMetadata ==
== ism-handling-retrieval ==
autonumber
opt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    Scheduler -> NCPeH: Trigger: \nAktualisierungsprozess von ISM anderer NCPeH Land-A starten
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SignedServiceMetadata) :ServiceMetadata
    NCPeH -> NCPeH: Signatur validieren (ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM aktualisieren (ServiceMetadata)
end
deactivate NCPeH

== 2. Integration von ISM ins EU-Webportal ==

opt Neue ServiceMetadata im NCPeH-FD verfügbar
    NCPeH -> Proxy: POST /events/ism/update
    note left: Ereignisbasierter Workflow statt Polling
    activate Proxy
    Proxy -> NCPeH: GET /ismlist
    activate NCPeH
    note left#Yellow: Hinweis: ab hier Auflösung der Objekte über ""domainobj-eped-b.yaml""
    loop Für jede ISM in ServiceMetadata.ISM
        NCPeH -> NCPeH: Anwendungen/Operationen der ISM zuordnen :ISMInternational
        NCPeH -> NCPeH: ISM in FHIR-Bundle integrieren(ISMInternational) :ISMInternationalList
        note left: jedes Listenelement als base64-enc FHIR Entry (Bundle.entry)
    end
    NCPeH --> Proxy: :ISMInternationalList
    note left: Liste ohne zusätzlichen Integritätsschutz auf Nachrichtenebene
    deactivate NCPeH
    Proxy -> Proxy: FHIR-Bundle validieren (ISMInternationalList)

== ism-handling-preparation ==
    'WebApp -> Proxy: POST /ism (ism_international_specific_html)
    loop Für jede ISMInternational in ISMInternationalList
        Proxy -> Proxy: ISM in HTML-Repräsentation umwandeln (ISMInternational):ISMInternationalHtml
        note right#DimGrey: vormals POST /ism/render
        alt Lektorierte Übersetzung der ISM vorhanden
            Proxy -> Proxy: Lektorierten deutschsprachigen HTML-GUI-Text übernehmen (ISMInternationalHtml) :ISMInternationalHtml.RepHtmlGerman
        else keine lektorierte Übersetzung vorhanden
            opt Translation Service verfügbar
            Proxy -> TranslationService: HTML-GUI-Text in deutsche Sprache übersetzen (ISMInternationalHtml)
            TranslationService --> Proxy: :ISMInternationalHtml.RepHtmlGerman
            end
        end
    end
    Proxy -> Buildprozess: POST /events/app/build
    note left: Ereignisbasierter Workflow statt Polling
    activate Buildprozess
    Buildprozess -> Proxy: GET /ism
    note right: kein Lazyloading der ISMs über WebApp, sondern statische Bereitstellung in WebApp-DeploymentArtifact
    note left#DimGrey: TODO: Request absichern oder hat\nder BP automatisch Zugriff?\nz.B. weil er ein Sidecar im selben\nNamespace ist\n\nTODO: Parameter für gültige\nAnwendungen notwendig?
    Proxy -> Proxy: gefilterte HTML-ISM-Liste zusammenstellen für gültige Anwendungen (ISMInternationalHtmlList):ISMInternationalHtmlList
    Proxy --> Buildprozess: :ISMInternationalHtmlList
    Buildprozess -> Buildprozess: Länderliste zu den benötigten Flaggen ableiten (ISMInternationalHtmlList) :countryCodes
    
    Buildprozess -> Proxy: GET /assets/flags?countryCodes=<countryCodes>
    note left: Batch-Endpoint für benötigte Länderflaggen
    Proxy --> Buildprozess: :CountryFlagList
    Buildprozess -> Buildprozess: Webapp bauen (ISMInternationalHtmlList, CountryFlagList, ...)
    note right: weitere Schritte für diesen UC nicht relevant, daher nicht aufgeführt
    deactivate Buildprozess
    ... Anschließend Deployment der Webapp auf dem Webserver ...
end

== ism-handling-display ==
    ... später: Benutzung durch LE-DE ...
    WebApp -> User: Übersicht aller verfügbaren Länder anzeigen
    activate WebApp
    User -> WebApp: Auswahl eines Landes für detaillierte ISM-Informationen (ISMInternationalHtml)
    WebApp -> WebApp: HTML-Resource laden (ISMInternationalHtml)
    User -> WebApp: Ausfüllen der detaillierten ISM-Ansicht (ISMInternationalHtml)
    WebApp -> WebApp: Validierung der Eingaben (ISMInternationalHtml)
    deactivate WebApp

== UC-Ende ==
    note over Proxy: ""WebApp -> Proxy: POST /ism (PatientIdentificationQuery)"" nicht mehr Bestandteil des UC 

deactivate Proxy
@enduml