@startuml ISM_bereitstellen_detailed

skinparam maxMessageSize 200
hide unlinked
'autonumber

actor "LE-DE" as User

participant "EU-Webportal\n(im Browser)" as WebApp
box "externe Services" #White
    participant "Translation Service" as TranslationService
end box
box "CI/CD-Pipeline" #faffe7
    control "Buildprozess\n(im Hintergrund)" as Buildprozess
    database "Quellen-\nRepository" as SrcRepo
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as Proxy
end box

actor "Anbieter" as Provider
actor "Systemadministrator" as Administrator
box "NCPeH-FD" #EAF2F8
control "Scheduler" as Scheduler <<internal>>
participant "NCPeH-FD" as NCPeH
end box

participant "eHDSI Configuration Service" as ConfServ

== Vorbedingungen ==
Administrator -> Scheduler: legt an
opt manuelle Übersetzung von ISMs gewünscht
    Provider -> SrcRepo: erstellt lektorierte, manuelle Übersetzung der ISMs
end
== 1. Täglicher Abruf von ServiceMetadata ==
== ism-handling-retrieval ==
autonumber
opt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    Scheduler -> NCPeH: Trigger: \nAktualisierungsprozess von ISM anderer NCPeH Land-A starten
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SignedServiceMetadata) :ServiceMetadata
    NCPeH -> NCPeH: Signatur validieren (ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM aktualisieren (ServiceMetadata)
end
deactivate NCPeH

== 2. Integration von ISM ins EU-Webportal ==

opt Neue ServiceMetadata.ISM im NCPeH-FD verfügbar
    NCPeH ->> Proxy: notifyIsmUpdateStep
    note right: Ereignisbasierter\nWorkflow statt Polling
    note left#Yellow: Hinweis: ab hier Auflösung der Objekte über ""domainobj-eped-b.yaml""\nAuflösung der StepIDs über ""wf-ism-bereitstellen.yaml""
    activate Proxy
    Proxy ->> Buildprozess: notifyWebAppBuildStep
    note left: TODO
    activate Buildprozess
    Proxy -> NCPeH: getEntitlementsStep
    activate NCPeH
    NCPeH --> Proxy: :CountryApplicationAuthorizationList
    deactivate NCPeH
    Proxy -> Proxy: Länderspezifische Rollenberechtigungen validieren (CountryApplicationAuthorizationList)
    deactivate Proxy

    Buildprozess -> NCPeH: getIsmListStep
    note left: TODO direkt an FD oder Forward durch Proxy?
    activate NCPeH
    loop Für jede ISM in ServiceMetadata.ISM
        NCPeH -> NCPeH: Anwendungen/Operationen der ISM zuordnen :ISMInternational
        NCPeH -> NCPeH: ISM in FHIR-Bundle integrieren (ISMInternational) :ISMInternationalList
        note left: jedes Listenelement als base64-enc FHIR Entry (Bundle.entry)
    end
    NCPeH --> Buildprozess: :ISMInternationalList
    note left: Liste ohne zusätzlichen\nIntegritätsschutz auf Nachrichtenebene
    deactivate NCPeH
    Buildprozess -> Buildprozess: FHIR-Bundle validieren (ISMInternationalList)

== ism-handling-preparation ==
    loop Für jede ISMInternational in ISMInternationalList
        Buildprozess -> Buildprozess: ISM in HTML-Repräsentation umwandeln (ISMInternational):ISMInternationalHtml
        alt Lektorierte Übersetzung der ISM vorhanden
            Buildprozess -> SrcRepo: Lektorierten deutschsprachigen HTML-GUI-Text übernehmen (ISMInternationalHtml)
            note right: TODO getHtmlAssetStep
            activate SrcRepo
            SrcRepo --> Buildprozess: :ISMInternationalHtml.RepHtmlGerman
            deactivate SrcRepo
        else keine lektorierte Übersetzung vorhanden
            opt Translation Service verfügbar
            Buildprozess -> TranslationService: HTML-GUI-Text in deutsche Sprache übersetzen (ISMInternationalHtml)
            activate TranslationService
            TranslationService --> Buildprozess: :ISMInternationalHtml.RepHtmlGerman
            deactivate TranslationService
            end
        end
    end
    'Proxy -> Buildprozess: triggerBuildStep
    Buildprozess -> Buildprozess: gefilterte ISMInternationalHtmlList zusammenstellen für gültige Anwendungen (ISMInternationalHtmlList) :ISMInternationalHtmlList
    note left: TODO abschaffen zugunsten\nToken-Scope-basierten Filtermechanismus
    Buildprozess -> Buildprozess: Länderliste zu den benötigten Flaggen ableiten (ISMInternationalHtmlList) :countryCodes
    note left: TODO abschaffen zugunsten\nToken-Scope-basierten Filtermechanismus

    Buildprozess -> SrcRepo: getFlagAssetsStep
    note right: TODO getFlagAssetsStep redesign
    activate SrcRepo
    SrcRepo --> Buildprozess: :CountryFlagList
    deactivate SrcRepo
    Buildprozess -> Buildprozess: Webapp bauen (ISMInternationalHtmlList, CountryFlagList, ...)
    note right
        weitere Schritte für diesen UC nicht relevant, daher nicht aufgeführt
    end note
    deactivate Buildprozess
    ... Anschließend Deployment der Webapp auf dem Webserver ...
end

== ism-handling-display ==
    ... später: Benutzung durch LE-DE ...
    WebApp -> User: Übersicht aller verfügbaren Länder anzeigen
    activate WebApp
    User -> WebApp: Auswahl eines Landes für detaillierte ISM-Informationen (ISMInternationalHtml)
    WebApp -> WebApp: HTML-Resource laden (ISMInternationalHtml)
    User -> WebApp: Ausfüllen der detaillierten ISM-Ansicht (ISMInternationalHtml)
    WebApp -> WebApp: Validierung der Eingaben (ISMInternationalHtml)
    deactivate WebApp

== UC-Ende ==
    note over Proxy: ""WebApp -> Proxy: POST /ism (PatientIdentificationQuery)"" nicht mehr Bestandteil des UC 

deactivate Proxy
@enduml