events {}
http {
    server {
        listen 80;

        location /http-proxy/api/v1/health {
            rewrite ^/http-proxy/api/v1/(.*)$ /$1 break;
            proxy_pass http://mock-proxy-basic:4010;
        }

        location /http-proxy/api/v1/ {
            rewrite ^/http-proxy/api/v1/(.*)$ /$1 break;
            proxy_pass http://mock-ism-service:4011;
        }

        location /ncpeh-fd/api/v1/ {
            rewrite ^/ncpeh-fd/api/v1/(.*)$ /$1 break;
            proxy_pass http://mock-ism-fd:4012;
        }
    }
}