@startuml ISM bereiststellen

skinparam maxMessageSize 200
autonumber

participant "EU-Webportal" as Webportal
box "NCPeH-Proxy" #White
    participant "HTTP-Proxy" as Proxy
end box
participant "NCPeH-FD" as NCPeH
participant "eHDSI Configuration Service" as ConfServ

== 1. Täglich Abruf von relevanten ISMs ==
alt ISMs zur bestimmten Uhrzeit noch nicht aktualisiert 
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SingedServiceMetadata)
    NCPeH -> NCPeH: ServiceMetada für ISM auswählen (SignedServiceMetadata): ISM_ServiceMetadata
    NCPeH -> NCPeH: Signatur und Schema validieren (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM speichern (ISM_ServiceMetadata)
    deactivate NCPeH
end

== 2. Tägliche Bereitstellung von ISMs ==
alt ISMs zur bestimmten Uhrzeit noch nicht aktualisiert
    Proxy -> NCPeH: GET /ISM
    activate Proxy
    activate NCPeH
    NCPeH --> Proxy: :Liste der ISMs
    deactivate NCPeH
    Proxy -> Proxy: Jede ISM auf Schema validieren (Liste der ISMs)
    Proxy -> Proxy: ISMs speichern
    deactivate Proxy
end

== 3. Integration von ISMs ins EU-Webportal ==
alt ISMs zur bestimmten Uhrzeit noch nicht aktualisiert
    Webportal -> Proxy: GET /ISM
    activate Webportal
    activate Proxy
    Proxy --> Webportal: :Liste von ISMs
    deactivate Proxy
    Webportal -> Webportal: Jede ISM auf Schema validieren (Liste der ISMs) 
    Webportal -> Webportal: Integration in Webapp (Liste der ISMs)
    deactivate Webportal
end
@enduml