@startuml ISM bereiststellen

skinparam maxMessageSize 200
autonumber

 
participant "__EU-Webportal__\n(Webserver)" as Webportal
box "NCPeH-Proxy" #White
    participant "HTTP-Proxy" as Proxy
end box
participant "NCPeH-FD" as NCPeH
participant "eHDSI Configuration Service" as ConfServ

== 1. Täglich Abruf von relevanten ISMs durch NCPeH-FD ==
alt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SingedServiceMetadata)
    NCPeH -> NCPeH: ServiceMetada für ISM auswählen (SignedServiceMetadata): ISM_ServiceMetadata
    NCPeH -> NCPeH: Signatur und Schema validieren (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM speichern (ISM_ServiceMetadata)
end
deactivate NCPeH



== 2. Integration von ISMs ins EU-Webportal ==
alt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    Webportal -> Proxy: GET /ISM?application=<LOINC_Code>
    activate Webportal
    activate Proxy
    
    Proxy -> NCPeH: GET /ISM?application=<LOINC_Code>
    activate Proxy
    activate NCPeH
    NCPeH -> NCPeH: ISMs für ePrescription laden(): FHIR_Bundle
    NCPeH --> Proxy: :FHIR_Bundle
    deactivate NCPeH
    Proxy -> Proxy: Jede ISM auf Schema validieren (FHIR_Bundle)
    deactivate Proxy

    
    Proxy --> Webportal: :FHIR_Bundle
    deactivate Proxy
    Webportal -> Webportal: Jede ISM auf Schema validieren (FHIR_Bundle) 
    Webportal -> Webportal: Integration in Webapp (FHIR_Bundle)
end
deactivate Webportal

@enduml