@startuml

skinparam maxMessageSize 200
autonumber
actor "LE-DE" as User
 box "EU-Webportal" #AliceBlue
  participant "EU-Webportal\n(Client-side WebApp)" as Webportal
  participant "Webserver" as Webserver
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as HTTP_Proxy
end box

participant "NCPeH-FD" as NCPeH
participant "NCPeH Land-A" as NCPeH_A


User -> Webportal: E-Rezepte zum Abruf auswählen(patient_identifier) :list_selected_presciption_retrieval
activate Webportal
User -> Webportal: Senden der Anfrage zum Abruf der ausgewählten E-Rezepte bestätigen()
Webportal -> Webportal: API-Request erstellen(LOINC_Code, Country_Code, list_selected_presciption_retrieval)
note over Webportal #DodgerBlue
    Nutzung von {Default-Auth-Header}
    für den API-Request
end note
== I_eHealth_Service ==
group#Gold ref
        Webportal o-> NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Request (Payload)}
        NCPeH ->o NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Request abgeschlossen (Payload)}
        NCPeH o-> NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Payloadverarbeitung (Payload_decrypted)} aufnehmen

end

activate NCPeH
group#Gold ref
        NCPeH o-> NCPeH: {Payloadverarbeitung (Payload_decrypted)} aufnehmen
end

NCPeH -> NCPeH: Gültigkeit der Assertion prüfen(IdentityAssertion)
NCPeH -> NCPeH: Daten aus API-Request extrahieren() :LOINC_Code, Country_Code, patient_identifier, list_selected_presciption_retrieval
NCPeH -> NCPeH: Autorisierung des LE-DE zum Abruf von E-Rezepten prüfen(IdentityAssertion, LOINC_Code)
NCPeH -> NCPeH: Land-A für ePrescription auf Zugriffsberechtigung prüfen(LOINC_Code, Country_Code)
NCPeH -> NCPeH: TRC Assertion laden(patient_identifier, IdentityAssertion) :trc_assertion_signed
NCPeH -> NCPeH: TRC Assertion auf Gültigkeit prüfen(trc_assertion_signed)
NCPeH -> NCPeH: IHE XCA.Retrieve-Anfrage erstellen(list_selected_presciption_retrieval, IdentityAssertion, trc_assertion_signed) :xca_retrieve_request
NCPeH -> NCPeH: Informationen über XCA.Retrieve Service Endpoint des Land-A laden() :xca_retrieve_endpoint_country_a
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
NCPeH -> NCPeH_A: IHE-Anfrage senden(xca_retrieve_endpoint_country_a, xca_retrieve_request)
activate NCPeH_A
NCPeH_A -> NCPeH_A: Angeforderte E-Rezepte des EU-Bürgers im Land-A ermitteln(xca_retrieve_request)
NCPeH_A --> NCPeH: :list_prescription_retrieved
deactivate NCPeH_A
NCPeH -> NCPeH: Non-Repudiation of Receipt speichern()
NCPeH -> NCPeH: Auf eHDSI und IHE Vorgaben prüfen(list_prescription_retrieved)
NCPeH -> NCPeH: Patient Identifier auf Übereinstimmung prüfen(patient_identifier, list_prescription_retrieved)
NCPeH -> NCPeH: E-Rezepte transkodieren(list_prescription_retrieved)
note over NCPeH
    Transkodierung der kodierten 
    Daten aus E-Rezepten
end note
NCPeH -> NCPeH: E-Rezepte in FHIR_Bundle integrieren (list_prescription_retrieved) :Payload
NCPeH -> NCPeH: Informationen über stattgefundene Events in HP Assurance Audit Trail Eintrag aufnehmen()
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
group#Gold ref
        NCPeH ->o NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Payloadverarbeitung abgeschlossen(Payload)}
        NCPeH o-> Webportal: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Response (Payload)}
        deactivate NCPeH
        Webportal ->o Webportal: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Response abgeschlossen (Payload)}
end


Webportal -> Webportal: Antwort gegen Schema validieren(list_prescription_retrieved)
deactivate NCPeH
Webportal -> Webportal: Patient Identifier auf Übereinstimmung prüfen(patient_identifier, list_prescription_retrieved)
Webportal -> Webportal: E-Rezepte in Webseite rendern(list_prescription_retrieved) :html_site
Webportal -> Webportal: Webseite anzeigen(html_site)
group#Gold opt
    User -> Webportal: Ausgewählte Original E-Rezepte anzeigen(list_prescription_retrieved): selected_original_eprescriptions
    Webportal -> Webportal: PDF/A-Dokumente extrahieren(selected_original_eprescriptions): pdf_eprescriptions
    Webportal -> Webportal: E-Rezepte im PDF/A-Format anzeigen(pdf_eprescriptions)
end
deactivate Webportal

@enduml