@startuml ISM bereiststellen

skinparam maxMessageSize 200
autonumber

actor "LE-DE" as LE_DE
 box "EU-Webportal" #AliceBlue
  participant "__EU-Webportal__\n(Client-side WebApp)" as WebApp
  participant "Browser" as Browser
  participant "Webserver" as Webserver
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as Proxy
    participant "Auth-Service" as AuthService
end box

participant "NCPeH-FD" as NCPeH


== Basis-Verbindungen und Client-Bereitstellung ==

LE_DE -> Browser: startet
Browser -> Webserver: WebApp per Link aufrufen
Webserver --> Browser: :WebApp
Browser --> WebApp: WebApp ausführen

note over WebApp, Browser
  WebApp wird im Browser ausgeführt.
end note

ref over LE_DE, WebApp, Browser, Webserver : Authentifizierung des LE-DE und der LEI-DE

LE_DE -> WebApp: Wählt die Anwendung ePresrciption aus
WebApp -> WebApp: Übersicht der Länder-B
LE_DE -> WebApp: Land-B auswählen












== 1. Täglich Abruf von relevanten ISMs ==
alt ISMs zur bestimmten Uhrzeit noch nicht aktualisiert 
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SingedServiceMetadata)
    NCPeH -> NCPeH: ServiceMetada für ISM auswählen (SignedServiceMetadata): ISM_ServiceMetadata
    NCPeH -> NCPeH: Signatur und Schema validieren (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ISM_ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM speichern (ISM_ServiceMetadata)
    deactivate NCPeH
end



== 2. Integration von ISMs ins EU-Webportal ==
alt ISMs zur bestimmten Uhrzeit noch nicht aktualisiert
    Webportal -> Proxy: GET /ISM
    activate Webportal
    activate Proxy
    
    Proxy -> NCPeH: GET /ISM
    activate Proxy
    activate NCPeH
    NCPeH --> Proxy: :Liste der ISMs
    deactivate NCPeH
    Proxy -> Proxy: Jede ISM auf Schema validieren (Liste der ISMs)
    Proxy -> Proxy: ISMs speichern
    deactivate Proxy
    
    
    Proxy --> Webportal: :Liste von ISMs
    deactivate Proxy
    Webportal -> Webportal: Jede ISM auf Schema validieren (Liste der ISMs) 
    Webportal -> Webportal: Integration in Webapp (Liste der ISMs)
    deactivate Webportal
end

@enduml