@startuml

skinparam maxMessageSize 200
autonumber
actor "EU-Bürger" as EUBuerger #LightGoldenRodYellow
actor "LE-DE" as User
entity "PIN-Dokument/\nHPIN-Dokument" as Document
box "EU-Webportal" #AliceBlue
  participant "EU-Webportal\n(Client-side WebApp)" as Webportal
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as HTTP_Proxy
    participant "Auth Service" as Auth_Service
end box

participant "NCPeH-FD" as NCPeH
participant "NCPeH Land-A" as NCPeH_A


group#Gold ref
        Webportal -> Auth_Service: 8.5.1 "Authentifizierung und Autorisierung des LE-DE"
end

User -> Webportal: Anwendung ePrescription auswählen()
activate Webportal
Webportal -> Webportal: Information über die ausgewählte Anwendung zwischenspeichern() :LOINC_Code




opt
    User -> Webportal: Öffnet Datenschutzbestimmungen des Herkunftslands, die vom EU-Webportal bereitgestellt werden
    create Document
    Webportal --> Document: Inhalt des Links anzeigen
    note over Document #Yellow
        Domänenobjekte:
        ""PINDocument""
        ""HPINDocument""
    end note
    Document -> User: Datenschutzbestimmungen werden angezeigt
    User -> EUBuerger: Datenschutzbestimmungen werden genannt und zur Kenntnis genommen

    alt Datenschutzbestimmungen ausdrucken
        PINDocument -> User: Ausdruck
        & User -> EUBuerger
    else Datenschutzbestimmungen digital bereitstellen
        PINDocument -> User: Link / QR-Code zum Download der Datenschutzbestimmungen
        & User -> EUBuerger
    else Datenschutzbestimmungshinweis geben
        User -> EUBuerger: Hinweis auf Website mit den Datenschutzbestimmungen wird gegeben
end

destroy PINDocument

end



User --> Webportal: Bestätigt Kenntnisnahme der Datenschutzbestimmungen

User -> Webportal: Wählt das Herkunftsland des EU-Bürgers aus

Webportal -> HTTP_Proxy: 
activate HTTP_Proxy
HTTP_Proxy --> Webportal: :fhir_bundle_ism
deactivate HTTP_Proxy
Webportal -> Webportal: Graphische Übersicht der EU-Länder für den Austausch von E-Rezepten erstellen(fhir_bundle_ism, LOINC_Code): html_country_overview
Webportal -> Webportal: anzeigen(html_country_overview)

User -> Webportal: Land-A auswählen()
Webportal -> Webportal: Ländercode für das ausgewählte Land-A zwischenspeichern() :Country_Code
Webportal -> Webportal: ISM für das gewählte Herkunftsland laden und anzeigen(fhir_bundle_ism) :ism_selected_country
Webportal -> Webportal: HTML-Seite erstellen(ism_selected_country) :html_ism_page
Webportal -> Webportal: Webseite anzeigen(html_ism_page)

User -> Webportal: Identitätsmerkmale und Zugriffsinformationen für Dokumentensuche in ISM eintragen() :patient_search_prameters, document_search_parameter
Webportal -> Webportal:  Format validieren(patient_search_prameters, document_search_parameter)
User -> Webportal: Senden der Anfrage zur Patient Identification bestätigen()
Webportal -> Webportal: Zugriffsinformationen für Dokumentensuche zwischenspeichern(document_search_parameter)
Webportal -> Webportal: API-Request für Patient Identification erstellen(patient_search_prameters, LOINC_Code, Country_Code)
note over Webportal #DodgerBlue
    Nutzung von {Default-Auth-Header}
    für den API-Request
end note  

Webportal -> Webportal: Fachliche Daten im inneren Request des ASL-Kanals an NCPeH-FD senden()

ref#Gold over Webportal, HTTP_Proxy, NCPeH
    8.5.3 "Nutzung einer autorisierten Verbindung zum NCPeD-FH"
end ref

'Webportal -> HTTP_Proxy: GET %HTTP-Proxy%/?app=<LOINC_Code>&cc=<Ländercode> \nAuthorization: DPoP <ncpehprx_access_token> DPoP <DPoP-Token-2>\nuser-agent:XYZ\nX-ncpeh-resource: Demographic\nPayload: <Chiffrat>

group#Gold ref
        NCPeH o-> NCPeH: {Payloadverarbeitung (Payload_decrypted)} aufnehmen
        activate NCPeH
end

NCPeH -> NCPeH: ISM des Land-A laden() :ism_coutry_a
NCPeH -> NCPeH: Suchparameter aus API-Request extrahieren(): patient_search_prameters
NCPeH -> NCPeH: Suchparameter aus API-Request auf Vorgaben aus ISM abgleichen(patient_search_prameters, ism_coutry_a)
NCPeH -> NCPeH: Identitätsdaten aus API-Request extrahieren() :patient_identity_traits
NCPeH -> NCPeH: IHE XCPD-Anfrage erstellen(patient_identity_traits, IdA) :xcpd_request
NCPeH -> NCPeH: Informationen über XCPD Service Endpoint des Land-A laden() :xcpd_endpoint_country_a
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
NCPeH -> NCPeH_A: IHE-Anfrage senden(xcpd_endpoint_country_a, xcpd_request)
activate NCPeH_A
NCPeH_A -> NCPeH_A: Weitere demographische Daten im Land-A ermitteln(xcpd_request)
NCPeH_A --> NCPeH: :xcpd_response
deactivate NCPeH_A
NCPeH -> NCPeH: Non-Repudiation of Receipt speichern()
NCPeH -> NCPeH: Auf eHDSI und IHE Vorgaben prüfen(xcpd_response)
NCPeH -> NCPeH: queryByParameters aus XCPD-Response auf Eindeutigkeit mit Identitätsdaten aus der WebApp-Anfrage prüfen(patient_identity_traits, xcpd_response)
NCPeH -> NCPeH: Demographische Daten des EU-Bürgers extrahieren(xcpd_response) :patient_demographic_data
NCPeH -> NCPeH: Demographische Daten in FHIR_Bundle integrieren(patient_demographic_data) :Payload_decrypted
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
group#Gold ref
        NCPeH ->o NCPeH: {Payloadverarbeitung abgeschlossen(Payload_decrypted)}
end

ref#Gold over Webportal, HTTP_Proxy, NCPeH
    8.5.3 "Nutzung einer autorisierten Verbindung zum NCPeD-FH"
end ref
deactivate NCPeH

Webportal -> Webportal: Antwort gegen Schema validieren(FHIR_Bundle_Demographic)
Webportal -> Webportal: Eindeutiges Patient Identifier zwischenspeichern(FHIR_Bundle_Demographic) :patient_identifier
Webportal -> Webportal: Webseite rendern(FHIR_Bundle_Demographic) :html_site
Webportal -> Webportal: Webseite anzeigen(html_site)
deactivate Webportal

@enduml