@startuml ISM bereiststellen

skinparam maxMessageSize 200
autonumber

 
'participant "__EU-Webportal__\n(Webserver)" as Webportal

box "EU-Webportal" #AliceBlue
    participant "Webapp" as WebApp
    participant "Webserver" as Webserver
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as Proxy
end box
participant "NCPeH-FD" as NCPeH
participant "eHDSI Configuration Service" as ConfServ

== 1. Täglich Abruf von ServiceMetadata ==
opt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    NCPeH -> ConfServ: SignedServiceMetadata relevanter NCPeH Land-A gemäß eHDSI abrufen
    activate NCPeH 
    activate ConfServ

    ConfServ --> NCPeH: :Liste der SignedServiceMetadata
    deactivate ConfServ

    NCPeH -> NCPeH: Schema und Signatur validieren (SingedServiceMetadata) :ServiceMetadata
    NCPeH -> NCPeH: Signatur validieren (ServiceMetadata)
    NCPeH -> NCPeH: Länderzuordnung prüfen (ServiceMetadata)
    NCPeH -> NCPeH: Serviceinformationen und ISM aktualisieren (ServiceMetadata)
end
deactivate NCPeH

== 2. Integration von ISMs ins EU-Webportal ==
opt Geplanter täglicher Aktualisierungszeitpunkt erreicht
    
    
    Proxy -> NCPeH: ISMs abrufen()
    activate Proxy
    activate NCPeH
    NCPeH -> NCPeH: Alle ISMs in FHIR-Bundle transformieren(ServiceMetadata.ISM): FHIR_Bundle
    NCPeH --> Proxy: :FHIR_Bundle
    deactivate NCPeH
    Proxy -> Proxy: Jede ISM gegen Schema validieren (FHIR_Bundle)
end
deactivate Proxy

WebApp -> Proxy: GET /ISM?application=<LOINC_Code>
activate WebApp
activate Proxy
Proxy --> WebApp: :FHIR_Bundle
deactivate Proxy
    
opt Bei Aufruf einer länderspezifischen Suchmaske
    WebApp -> WebApp: Rendering und Anzeige der entsprechenden ISM(FHIR_Bundle)
end


@enduml