@startuml

skinparam maxMessageSize 200
autonumber
actor "LE-DE" as User
participant "Browser" as Browser
 box "EU-Webportal" #AliceBlue
  participant "EU-Webportal\n(Client-side WebApp)" as Webportal
  participant "Webserver" as Webserver
end box

box "NCPeH-Proxy" #FloralWhite
    participant "HTTP-Proxy" as HTTP_Proxy
end box

participant "NCPeH-FD" as NCPeH
participant "NCPeH Land-A" as NCPeH_A

== Basis-Verbindungen und Client-Bereitstellung ==

User -> Webportal: Webseite mit der Übersicht der einlösbaren E-Rezepte auswählen()
activate Webportal
Webportal -> Webportal: Webseite rendern und anzeigen()
User -> Webportal: Behandlungsbeziehung zum EU-Bürger bestätigen()
User -> Webportal: Senden der Anfrage zur Auflistung von einlösbaren E-Rezepten bestätigen()
Webportal -> Webportal: Patient Identifier laden() :patient_identifier
Webportal -> Webportal: Zugriffsinformationen für Dokumentensuche laden() :document_search_parameter
Webportal -> Webportal: API-Request erstellen(LOINC_Code, Country_Code, patient_identifier, document_search_parameter):Payload
note over Webportal #DodgerBlue
    Nutzung von {Default-Auth-Header}
    für den API-Request
end note

== I_Health_Service ==
group#Gold ref
        Webportal o-> NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Request (patient_identifier)}
        NCPeH ->o NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Request abgeschlossen (patient_identifier)}
        NCPeH o-> NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Payloadverarbeitung (Payload_decrypted)} aufnehmen

end

activate NCPeH

NCPeH -> NCPeH: Daten aus API-Request extrahieren() :LOINC_Code, Country_Code, patient_identifier, document_search_parameter

NCPeH -> NCPeH: Gültigkeit der Assertion prüfen(IdentityAssertion)
NCPeH -> NCPeH: Land-A für ePrescription auf Zugriffsberechtigung prüfen(LOINC_Code, Country_Code)
NCPeH -> NCPeH: Autorisierung des LE-DE zur Auflistung von einlösbaren E-Rezepten prüfen(IdentityAssertion, LOINC_Code)
NCPeH -> NCPeH: SAML2.0 Assertion erstellen(IdentityAssertion.NameID, patient_identifier, document_search_parameter) :trc_assertion
NCPeH -> NCPeH: SAML Assertion signieren(trc_assertion, PrK_SEAL_eHDSI) :trc_assertion_signed
NCPeH -> NCPeH: Assertion für die Dauer der Gültigkeit speichern (trc_assertion_signed)
NCPeH -> NCPeH: HP Assurance audit trail Eintrag speichern(IdentityAssertion, patient_identifier)
NCPeH -> NCPeH: IHE XCA.Query-Anfrage erstellen(patient_identifier, IdentityAssertion, trc_assertion_signed) :xca_query_request
NCPeH -> NCPeH: Informationen über XCA.Query Service Endpoint des Land-A laden() :xca_endpoint_country_a
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
NCPeH -> NCPeH_A: IHE-Anfrage über TESTA-ng senden(xca_endpoint_country_a, xca_query_request)
activate NCPeH_A
NCPeH_A -> NCPeH_A: Einlösbare E-Rezepte des EU-Bürgers im Land-A ermitteln(xca_query_request)
NCPeH_A --> NCPeH: :xca_query_response
deactivate NCPeH_A
NCPeH -> NCPeH: Non-Repudiation of Receipt speichern()
NCPeH -> NCPeH: Auf eHDSI und IHE Vorgaben prüfen(xca_query_response)
NCPeH -> NCPeH: Patient Identifiers auf Übereinstimmung prüfen(patient_identifier, xca_query_response.patientId)
NCPeH -> NCPeH: Kodierte Angaben zu E-Rezepten transkodieren(xca_query_response) :metadata_eprescriptions
note over NCPeH
    Kodierte Angaben zu 
    Generic Substance Name,
    Dosage Form und Strength.
end note
NCPeH -> NCPeH: Metadata in FHIR_Bundle integrieren (metadata_eprescriptions) :Payload_decrypted
NCPeH -> NCPeH: Non-Repudiation of Origin speichern()
group#Gold ref
        NCPeH ->o NCPeH: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Payloadverarbeitung abgeschlossen(Payload_decrypted)}
        NCPeH o-> Webportal: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Response (Payload)}
        deactivate NCPeH
        Webportal ->o Webportal: UC "Nutzung einer autorisierten Verbindung zum NCPeH-FD" {Autorisierter Response abgeschlossen (Payload)}
end

Webportal -> Webportal: Antwort gegen Schema validieren(fhir_bundle_metadata_eprescriptions)
Webportal -> Webportal: Patient Identifiers auf Übereinstimmung prüfen(patient_identifier, fhir_bundle_metadata_eprescriptions)
Webportal -> Webportal: Metadaten zu E-Rezepten des EU-Bürgers Webseite rendern(fhir_bundle_metadata_eprescriptions) :html_site
Webportal -> Webportal: Webseite anzeigen(html_site)
deactivate Webportal

@enduml